version: "3.8"
services:
  nginx:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/whale-nginx:latest
    ports:
      - "80:80"
    depends_on: [app1, app2]

  app1:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/whale-app:latest
    environment:
      - PORT=3000

  app2:
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/whale-app:latest
    environment:
      - PORT=3000